/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wPJrjzL5ccC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function generate() {
  const [savedRecipes, setSavedRecipes] = useState([])
  const handleRecipeSave = (recipe) => {
    setSavedRecipes([...savedRecipes, recipe])
  }
  return (
    <div className="w-full max-w-4xl mx-auto py-12 px-4 md:px-6">
      <header className="flex justify-between items-center mb-8">
        <nav className="flex gap-4">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Generate
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Cookbook
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Meal Plans
          </Link>
        </nav>
      </header>
      <div className="grid gap-8">
        <div>
          <h2 className="text-3xl font-bold mb-4">Upload Photos</h2>
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="Photo 1"
                width={300}
                height={300}
                className="w-full h-full object-cover"
              />
            </div>
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="Photo 2"
                width={300}
                height={300}
                className="w-full h-full object-cover"
              />
            </div>
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="Photo 3"
                width={300}
                height={300}
                className="w-full h-full object-cover"
              />
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-3xl font-bold mb-4">Dietary Restrictions</h2>
          <Textarea
            placeholder="Enter your dietary restrictions (e.g., vegan, gluten-free, nut allergy)"
            className="w-full"
            rows={3}
          />
        </div>
        <div>
          <Button className="w-full">Generate Recipes</Button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card>
            <CardContent>
              <img
                src="/placeholder.svg"
                alt="Recipe 1"
                width={400}
                height={300}
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-xl font-bold mb-2">Grilled Salmon with Roasted Vegetables</h3>
                <p className="text-muted-foreground">
                  A delicious and healthy meal featuring grilled salmon and a variety of roasted vegetables.
                </p>
                <div className="flex justify-center items-center mt-4">
                  <Button
                    variant="outline"
                    onClick={() =>
                      handleRecipeSave({
                        name: "Grilled Salmon with Roasted Vegetables",
                        ingredients: ["Salmon", "Vegetables", "Olive oil", "Seasonings"],
                        instructions: ["Preheat grill", "Season salmon", "Grill salmon", "Roast vegetables", "Serve"],
                      })
                    }
                  >
                    Save to Cookbook
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                src="/placeholder.svg"
                alt="Recipe 2"
                width={400}
                height={300}
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-xl font-bold mb-2">Vegetarian Stir-Fry with Tofu</h3>
                <p className="text-muted-foreground">
                  A flavorful vegetarian stir-fry with crispy tofu and a variety of fresh vegetables.
                </p>
                <div className="flex justify-center items-center mt-4">
                  <Button
                    variant="outline"
                    onClick={() =>
                      handleRecipeSave({
                        name: "Vegetarian Stir-Fry with Tofu",
                        ingredients: ["Tofu", "Vegetables", "Soy sauce", "Sesame oil"],
                        instructions: [
                          "Prepare tofu",
                          "Stir-fry vegetables",
                          "Add tofu",
                          "Season with soy sauce and sesame oil",
                          "Serve",
                        ],
                      })
                    }
                  >
                    Save to Cookbook
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                src="/placeholder.svg"
                alt="Recipe 3"
                width={400}
                height={300}
                className="w-full h-48 object-cover rounded-t-md"
              />
              <div className="p-4">
                <h3 className="text-xl font-bold mb-2">Baked Chicken with Herb Roasted Potatoes</h3>
                <p className="text-muted-foreground">
                  A classic and comforting meal featuring tender baked chicken and flavorful roasted potatoes.
                </p>
                <div className="flex justify-center items-center mt-4">
                  <Button
                    variant="outline"
                    onClick={() =>
                      handleRecipeSave({
                        name: "Baked Chicken with Herb Roasted Potatoes",
                        ingredients: ["Chicken", "Potatoes", "Herbs", "Olive oil"],
                        instructions: [
                          "Preheat oven",
                          "Season chicken",
                          "Roast chicken",
                          "Prepare potatoes",
                          "Roast potatoes",
                          "Serve",
                        ],
                      })
                    }
                  >
                    Save to Cookbook
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
